config/routes.rb
Rails.application.routes.draw do
  

  

  get 'rewards/create'

  get 'rewards/new'

  get 'rewards/index'

  get 'rewards/edit'

  get 'rewards/update'

  get 'rewards/destroy'

  root :to => 'users#index'
  resources :user_sessions
  resources :users
  resources :projects
  resources :pledges, only: [:create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
      # user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    
    user ||= User.new
    can :edit, Project, :owner_id => user.id
    can :update, Project, :owner_id => user.id
    

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :backer, class_name: 'User'
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

	belongs_to :owner, class_name: 'User'
	has_many :backers, through: :pledges, class_name: 'User'
	has_many :rewards
	has_many :pledges
	belongs_to :category

	accepts_nested_attributes_for :rewards, :allow_destroy => true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_ordered_taggable
  acts_as_ordered_taggable_on :interests
  scope :by_join_date, order("created_at DESC")
  authenticates_with_sorcery!

  validates :password, length: {minimum: 4}
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id'

  has_many :pledges, foreign_key: 'backer_id'
  has_many :backed_projects, through: :pledges, source: :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login


private

 def not_authenticated
   redirect_to login_path, alert: "Please, log the fuck in."
 end
 
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  def create

  	@pledge = Pledge.new(pledge_params)
  	@pledge.backer = current_user

  	if @pledge.save
      response.headers['X-Message'] = "You've successfully made a pledge"
    else
      response.headers['X-Message'] = "Failed to create pledge"
    end

  	respond_to do |format|
  		format.js {}
  	end
  end

  private 

  def pledge_params
  	params.require(:pledge).permit(:amount, :project_id)
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :days_left

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user
    if @project.save
      redirect_to project_path(@project.id)
    else
      render :new, alert: 'There was an error'
    end
  end

  def edit
  	@project = Project.find(params[:id])
    authorize! :edit, @project

  end
  
  def update
  	@project = Project.find(params[:id])
    authorize! :update, @project
  	if @project.update(project_params)
  		redirect_to project_path(@project)
  	else
  		render :edit
  	end
  end

  def delete
  end

  def destroy
  end


  private

  def days_left
    days = (@project.end_date - @project.start_date)
    (days / 86400).round
  end

  def project_params
  	params.require(:project).permit(:name, :funding_goal, :description,
                                    :start_date, :end_date, :category_id,
                                    rewards_attributes: [:id, :amount, :backer_limit, :description, :_destroy])

  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def create
    @reward = Reward.new
  end

  def new
    @reward = Reward.new
  end

  def index
    @rewards = Reward.all
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update

    if @reward.save
      redirect_to project_path(@reward.project.id)
    else
      render :edit
    end
  end

  def destroy

    
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  
  def new
    @user = User.new
  end

  def create
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to(:users, notice: 'Login successful')
  	else
  	  flash.now[:alert] = "Login failed"
  	  render action: 'new'
  	end
  end

  def destroy
  	logout
  	redirect_to(:users, notice: 'Logged out!')
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        UserMailer.welcome_email(@user).deliver
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdfunderAlt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> <!-- Adds authenticity token to every page -->
</head>
<body>

  <div id="nav">
    <%= link_to "Projects", projects_path %>
    <% if current_user %>
      <%= link_to "Create Project", new_project_path %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %><br>
      <%= "Signed in as: #{current_user.first_name}" %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
  <%= yield %>

</body>
</html>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
	<div>
		<%= f.label :amount, "Pledge Amount: " %>
		<%= f.text_field :amount %>
	</div>
	<div>
		<%= f.label :backer_limit, "Backer Limit: " %>
		<%= f.text_field :backer_limit %>
	</div>
	<div>
		<%= f.label :description, "Description: " %>
		<%= f.text_area :description %>
	</div>

	<%= link_to_remove_association "remove reward", f %>
</div>

app/views/projects/edit.html.erb
<%= @project.name %>

<%= form_for @project do |f| %>
	<div>
		<%= f.label :name, 'Give your project a name: ' %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :description, "What's your project about? " %>
		<%= f.text_area :description %>
	</div>
	<div>
		<%= f.label :funding_goal, "What's your projects funding goal? " %>
		<%= f.number_field :funding_goal %>
	</div>
	<div>
		<%= f.label :start_date, "When should the crowd funding start? " %>
		<%= f.date_field :start_date %>
	</div>
	<div>
		<%= f.label :end_date, "When should the crowd funding end? " %>
		<%= f.date_field :end_date %>
	</div>
	<div>
		<%= f.label "Category", "What category does this belong to?" %>
		<%= f.collection_select :category_id, Category.all, :id, :name  %>
	</div>
	<div>
		<%= f.fields_for :rewards do |reward_fields| %>
			<%= render 'reward_fields', f: reward_fields %>
		<% end %>
		<%= link_to_add_association "Add reward", f, :rewards %>
	</div>

	<%= f.submit "Save Changes" %>
	<%= link_to "Back", project_path(@project) %>

<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% @projects.each do |project| %>
	<div>
		<%= project.name %>
	</div>

	<div>
		<%= link_to 'Check it out', project_path(project) %>
	</div>
<% end %>

app/views/projects/new.html.erb
<h1>Create New Project</h1>

<%= form_for @project do |f| %>
	

	<div>
		<%= f.label :name, 'Give your project a name: ' %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :description, "What's your project about? " %>
		<%= f.text_area :description %>
	</div>
	<div>
		<%= f.label :funding_goal, "What's your projects funding goal? " %>
		<%= f.number_field :funding_goal %>
	</div>
	<div>
		<%= f.label :start_date, "When should the crowd funding start? " %>
		<%= f.date_field :start_date %>
	</div>
	<div>
		<%= f.label :end_date, "When should the crowd funding end? " %>
		<%= f.date_field :end_date %>
	</div>
	<div>
		<%= f.label :cat_name, "What category does this belong to?" %>
		<%= f.text_area :cat_name %>
	</div>
	<div>
		<%= f.fields_for :rewards do |reward_fields| %>
			<%= render 'reward_fields', f: reward_fields %>
		<% end %>
		<%= link_to_add_association "Add reward", f, :rewards %>
	</div>
	<%= f.submit "Create your project!" %>

<% end %>

app/views/projects/show.html.erb
<%= @project.name %>
<%= link_to "Edit Project", edit_project_path(@project.id) %> <br>
<div id="pledge_response"></div>
<p> Description: <%= @project.description %> </p>
<p> Funding goal: $<%= @project.funding_goal %> </p>
<p> Days Left: <%= days_left %> </p>
<p> Category: <%= @project.category.try(:name) %></p>

<h2>Rewards</h2>
<% @project.rewards.each do |reward| %>

	<div class="reward" data-reward-amount="<%= reward.amount %>" data-project-id="<%= @project.id %>">
		<div>
			<p> For $<%= reward.amount %></span> </p>
		</div>
		<div>
			<p> You get: <%= reward.description %> </p>
		</div>
	</div>
<% end %>

app/views/rewards/_rewards_fields.html.erb
<div>
	<div>
		<%= f.label :amount, "Pledge Amount: " %>
		<%= f.text_field :amount %>
	</div>
	<div>
		<%= f.label :backer_limit, "Backer Limit: " %>
		<%= f.text_field :backer_limit %>
	</div>
	<div>
		<%= f.label :description, "Description: " %>
		<%= f.text_area :description %>
	</div>
</div>

app/views/rewards/create.html.erb
<h1>Rewards#create</h1>
<p>Find me in app/views/rewards/create.html.erb</p>

app/views/rewards/destroy.html.erb
<h1>Rewards#destroy</h1>
<p>Find me in app/views/rewards/destroy.html.erb</p>

app/views/rewards/edit.html.erb
<h1>Rewards#edit</h1>
<p>Find me in app/views/rewards/edit.html.erb</p>

app/views/rewards/index.html.erb
<h1>Rewards#index</h1>
<p>Find me in app/views/rewards/index.html.erb</p>

app/views/rewards/new.html.erb
<h1>Rewards#new</h1>
<p>Find me in app/views/rewards/new.html.erb</p>

app/views/rewards/update.html.erb
<h1>Rewards#update</h1>
<p>Find me in app/views/rewards/update.html.erb</p>

app/views/user_sessions/_form.html.erb
 
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>

  

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Please Login</h1>

<%= render 'form' %>

<%= link_to 'back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h1>Projects You've Started</h1>

<% @user.owned_projects.each do |project| %>
	<div>
		<%= project.name %>
	</div>

	<div>
		<%= link_to 'Check it out', project_path(project) %>
	</div>
<% end %>



<h1>Your Pledges</h1>

<% @user.backed_projects.each do |project| %>
	<div>
		<%= project.name %>
	</div>

	<div>
		<%= link_to 'Check it out', project_path(project) %>
	</div>
<% end %>